// Placeholder for WASM module
// Real file will be generated by `wasm-pack build`
// Run: rustup target add wasm32-unknown-unknown && npm run build:wasm

export default async function init() {
    console.log("[WASM] Mock init called (Real WASM build missing)");
    return Promise.resolve();
}

export function compare_stats(statsA, statsB) {
    console.log("[WASM] Mock compare_stats called");
    // Simple JS implementation for fallback
    const delta = {};
    const keys = new Set([...Object.keys(statsA), ...Object.keys(statsB)]);
    
    keys.forEach(key => {
        const valA = statsA[key] || 0;
        const valB = statsB[key] || 0;
        delta[key] = valB - valA;
    });
    
    return delta;
}
