const mongoose = require('mongoose');

const ManifestItemSchema = new mongoose.Schema({
    hash: { type: Number, required: true, index: true },
    name: { type: String, index: true },
    icon: String,
    hasIcon: Boolean,
    secondaryIcon: String,
    secondaryOverlay: String,
    secondarySpecial: String,
    screenshot: String,
    itemTypeDisplayName: String,
    flavorText: String,
    uiItemDisplayStyle: String,
    itemTypeAndTierDisplayName: String,
    displaySource: String,
    tooltipStyle: String,
    action: mongoose.Schema.Types.Mixed,
    inventory: mongoose.Schema.Types.Mixed,
    stats: mongoose.Schema.Types.Mixed,
    equippingBlock: mongoose.Schema.Types.Mixed,
    translationBlock: mongoose.Schema.Types.Mixed,
    preview: mongoose.Schema.Types.Mixed,
    quality: mongoose.Schema.Types.Mixed,
    acquireRewardSiteHash: Number,
    acquireUnlockHash: Number,
    sockets: mongoose.Schema.Types.Mixed,
    talentGrid: mongoose.Schema.Types.Mixed,
    perks: mongoose.Schema.Types.Mixed,
    loreHash: Number,
    summaryItemHash: Number,
    animations: [mongoose.Schema.Types.Mixed],
    allowActions: Boolean,
    links: [mongoose.Schema.Types.Mixed],
    doesPostmasterPullHaveSideEffects: Boolean,
    nonTransferrable: Boolean,
    itemCategoryHashes: [Number],
    specialItemType: Number,
    itemType: Number,
    itemSubType: Number,
    classType: Number,
    breakerType: Number,
    equippable: Boolean,
    damageTypeHashes: [Number],
    damageTypes: [Number],
    defaultDamageType: Number,
    defaultDamageTypeHash: Number,
    seasonHash: Number,
    isWrapper: Boolean,
    traitIds: [String],
    traitHashes: [Number],
    // Add other fields as needed, using Mixed for complex nested objects to avoid strict schema validation errors initially
    json: { type: mongoose.Schema.Types.Mixed } // Store the full raw JSON just in case
}, { strict: false });

module.exports = mongoose.model('ManifestItem', ManifestItemSchema);
